### ISSUE TITLE
Add github code link for 'Natural Language is All a Graph Needs'

### ISSUE THREAD

**Issue by RuosongYe** [XiaoxinHe/Awesome-Graph-LLM#10]
https://github.com/agiresearch/InstructGLM

Do you mind if I want a help for adding this official github code link to (arXiv 2023.08) Natural Language is All a Graph Needs 

Thank you so much.

**Comment by XiaoxinHe** [comment]
Hi Ruosong,

Thanks for the updates!

We have incorporated the github code link into our repo. Please check [this commit](https://github.com/XiaoxinHe/Awesome-Graph-LLM/commit/28dfdb53c3f199d7d3ecb2c26dba02ea800dbd34).

Best,
Xiaoxin
