### ISSUE TITLE
Add a new paper

### ISSUE THREAD

**Issue by ZhuYun97** [XiaoxinHe/Awesome-Graph-LLM#16]
Hi Xiaoxin,

We have recently published a paper titled "Efficient Tuning and Inference for Large Language Models on Textual Graphs ". This paper introduces an efficient training and inference algorithm specifically designed for Large Language Models (LLMs) on text-attributed graphs.

We would greatly appreciate it if you could include this paper in your repository, specifically in the "Node Classification" section.
- (*arXiv 2024.01*) Efficient Tuning and Inference for Large Language Models on Textual Graphs [[pdf](https://arxiv.org/abs/2401.15569)][[code](https://github.com/ZhuYun97/ENGINE)]

Best,
Yun

**Comment by XiaoxinHe** [comment]
Hi Yun,

Thank you for bringing this to our attention. We have added this paper to our repo.

Best,
Xiaoxin
