### ISSUE TITLE
Add a new dataset & benchmark

### ISSUE THREAD

**Issue by junhongmit** [XiaoxinHe/Awesome-Graph-LLM#29]
Hi Xiaoxin,

Thanks for this comprehensive collection of works! I would like to add this interesting work into the dataset section:
- When Heterophily Meets Heterogeneity: New Graph Benchmarks and Effective Methods (https://arxiv.org/abs/2407.10916)

The open-source GitHub repository can be found at https://github.com/junhongmit/H2GB.

Thanks very much!

Best,
Junhong

**Comment by XiaoxinHe** [comment]
Hi Junhong,

Thank you for bringing this great benchmark work to our attention. However, it seems to me that this is not a benchmark designed for graph LLMs, as there are no text attributes, or the text attributes have been encoded as vectors, with the raw text not available. In that case, this dataset may not be suitable for graph LLMs, where raw text attributes are important. If my understanding is incorrect, please feel free to correct me. Thank you

**Comment by junhongmit** [comment]
Hi Xiaoxin,

That’s a great point! Text attribute is indeed an important input for LLM. I can let you know if this graph benchmark is updated with text attribute in it. Thanks for looking into it!

Best,
Junhong
