### ISSUE TITLE
Potential related papers

### ISSUE THREAD

**Issue by PeterGriffinJin** [XiaoxinHe/Awesome-Graph-LLM#3]
Dear authors,

Thank you so much for making this great repo! Could you please add these three papers? The first two are about representation learning with large pretrained language models on graphs associated with textual information, while the last is about pretraining large language models on text-rich networks.

[1] Heterformer: A Transformer Architecture for Node Representation Learning on Heterogeneous Text-Rich Networks. KDD 2023.

[2] Edgeformers: Graph-Empowered Transformers for Representation Learning on Textual-Edge Networks. ICLR 2023.

[3] Patton: Language Model Pretraining on Text-rich Networks. ACL 2023.

Thanks!

**Comment by XiaoxinHe** [comment]
Hi,

Thank you for your message and for your interest in our repository. We appreciate your suggestion to include the papers you mentioned. However, I apologize for any confusion caused.

In this repository, we explicitly distinguish between “LMs” and “LLMs”. We use “LMs” to refer to relatively small language models that can be trained and tuned with an academic lab budget. We use “LLM” to refer to very large language models that are capable of learning complex patterns, such as GPT-3/4. These models typically have tens or hundreds of billions of parameters and require significant computational resources to train and use. 

The papers you mentioned appear to be related to representation learning with smaller language models (LMs) like BERT, and their application in graph-based scenarios. While these papers are certainly valuable in their own right, they fall outside the scope of this particular repository, which primarily focuses on LLMs.

We appreciate your understanding. Thank you again for your contribution!

**Comment by PeterGriffinJin** [comment]
Thank you so much for the clarification!

I would also like to provide a paper that contains 20 text-attributed networks of very high quality from different domains from Microsoft Academic Graph.

![image](https://github.com/XiaoxinHe/Awesome-Graph-LLM/assets/48234654/2d2009a0-dd57-4028-8dff-392a721ed8c7)

This could be a future testbed for developing better LLMs for graphs.
