### ISSUE TITLE
Add a new dataset & benchmark  paper

### ISSUE THREAD

**Issue by Zhuofeng-Li** [XiaoxinHe/Awesome-Graph-LLM#33]
Hi Xiaoxin,

Thanks for this comprehensive collection of works!

I want to share our recent TEG (textual-edge graph featuring rich
textual descriptions on nodes and edges) Datasets and Benchmark work published in NeurIPS 2024. 

- (NeurIPS 2024) TEG-DB: A Comprehensive Dataset and Benchmark of Textual-Edge Graphs [[pdf](https://arxiv.org/abs/2406.10310)][[code](https://github.com/Zhuofeng-Li/TEG-Benchmark/tree/main)][[datasets](https://huggingface.co/datasets/ZhuofengLi/TEG-Datasets/tree/main)]

Best,
Zhuofeng

**Comment by XiaoxinHe** [comment]
Hi Zhuofeng,

Thanks for sharing the new work. I've added it to the repo. Thanks!
