### ISSUE TITLE
We would like to introduce another paper that complements this topic: "GIMLET: A Unified Graph-Text Model for Instruction-Based Molecule Zero-Shot Learning." 

### ISSUE THREAD

**Issue by zhao-ht** [XiaoxinHe/Awesome-Graph-LLM#4]
Thank you for sharing your insightful paper list!
We would like to introduce another paper that complements this topic: "GIMLET: A Unified Graph-Text Model for Instruction-Based Molecule Zero-Shot Learning." This paper integrates the graph modality into the language model and employs an instruction-based learning approach to address graph property prediction tasks. We would be delighted if our suggestion contributes to the enrichment of this awesome paper list ☺️ !

**Comment by XiaoxinHe** [comment]
Thank you for contributing to this repository!
We have added this paper under the "Graph Classification/Regression" category.

**Comment by zhao-ht** [comment]
Thank you for your feedback and for maintaining this fantastic paper list!
