### ISSUE TITLE
Potential related work

### ISSUE THREAD

**Issue by Samyu0304** [XiaoxinHe/Awesome-Graph-LLM#8]
Hi, thanks for this awesome repo! We would like to introduce a related work on using the graph structure of general tasks to enhance complex reasoning with LLMs "Thought Propagation: An Analogical Approach to Complex Reasoning with Large Language Models". We hope our suggestion could enrich this awesome paper list ☺️ !

**Comment by XiaoxinHe** [comment]
Hi Junchi,

Thanks for bringing "thought propagation" to our attention. We greatly appreciate your contribution to this repository.

I have included the paper in the "Prompting" section. You can find it [here](https://github.com/XiaoxinHe/Awesome-Graph-LLM/commit/fd4dc8a17b2efe11c3cf49a1fded73116ee67142).


Best,
Xiaoxin
