### ISSUE TITLE
A new position paper "Integrating Graphs with Large Language Models: Methods and Prospects"

### ISSUE THREAD

**Issue by zyzisastudyreallyhardguy** [XiaoxinHe/Awesome-Graph-LLM#9]
Hi Xiaoxin,

We have just arxiv a new position paper "Integrating Graphs with Large Language Models: Methods and Prospects", which discusses the current paradigms and open questions regarding the integration of graphs and LLMs.

Could you please kindly include this paper in your repo? Much appreciated!

Here is the link to the paper:
https://arxiv.org/abs/2310.05499

Warmest Regards,
Yizhen Zheng

**Comment by XiaoxinHe** [comment]
Hi Yizhen,

Thanks for bringing this paper to our attention. 

I have included it in the "Datasets, Benchmarks & Surveys" section. You can find it [here](https://github.com/XiaoxinHe/Awesome-Graph-LLM/commit/f6c31225513e880731b2161857d6cdffd036cce3).


Best,
Xiaoxin

**Comment by zyzisastudyreallyhardguy** [comment]
Hi Xiaoxin,

The paper has now been accepted by IEEE Intelligent Systems and will be published in November. Could you please update this information?

Thank you!

Warmest Regards,
Yizhen Zheng

**Comment by XiaoxinHe** [comment]
Thanks for letting me know! I have updated this information.

Best,
Xiaoxin
